### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rohit1290** [autohub7/Options_Margin_Calc#1]
Can you please share the link from where you got the margin calculator formulas?

**Comment by autohub7** [comment]
Hi rohit1290, 

As I said in README, it's an obsolete project. When I trade options with Optionshouse 3 years ago, they had a webpage for margin requirements for different options strategies. I had to create the margin calculator for myself to avoid margin calls. Since margin requirement is different for each strategy and brokerage, you should contact your brokerage to get these information

Thanks, 
Steven

**Comment by rohit1290** [comment]
Thanks
